### ISSUE TITLE
ERROR_NOT_AUTHORIZED when creating real time multiplayer room SDKOX GPG plugin

### ISSUE THREAD

**Issue by oct-test** [sdkbox/sdkbox-sample-gpg#11]
I have setup **real-time multiplayer** for my Android game on Play Console. The game is currently in open beta and now I wanted to add the multiplayer feature. I have created 2 [linked applications](https://developers.google.com/games/services/console/enabling) for my debug and release certificates.

**Code:**

  ```
  gpg::RealTimeRoomConfig config = gpg::RealTimeRoomConfig::Builder().SetMinimumAutomatchingPlayers(1).SetMaximumAutomatchingPlayers(4).Create();
                _game_services->RealTimeMultiplayer().
                CreateRealTimeRoom(config,
                                   this,
                                   [this](gpg::RealTimeMultiplayerManager::RealTimeRoomResponse const & response) {

                                       string msg;

                                       if (gpg::MultiplayerStatus::VALID == response.status) {
                                           msg = "Room created: ";
                                           msg += response.room.Id();
                                           _txtStat->setString(msg);
                                           //cocos2d::log("create room success");
                                           CCLOG("create room success");
                                           setRoom(response.room);
                                           cocos2d::log("create room");
                                       } else {
                                           msg = "Room failed: ";
                                           msg += to_str(response.status);
                                           _txtStat->setString(msg);
                                           CCLOG("create room failed");
                                           cocos2d::log("create room fail");
                                       }
                                   });
```

When I deploy the build on an Android device, the code is able to sign in using the test accounts but the room creation code generates "[ERROR_NOT_AUTHORIZED](https://developers.google.com/games/services/cpp/api/namespace/gpg#multiplayerstatus)" error.

When I test my game settings with the Google's Android sample project, it works without any issues. Are there any known issues with the SDKBOX GPGS plugin?

I would appreciate any suggestions and thoughts on this topic. Thank you.

**Comment by hugohuang1111** [comment]
i check the cpp proejct. and find it use `CreateRoom` to create room. 

https://github.com/sdkbox/sdkbox-sample-gpg/blob/master/cpp/Classes/RealTimeMultiplayerScene.cpp#L99

**Comment by oct-test** [comment]
Google Play Services Version: 12211000
I get this log in Android Studio console:
E/GamesNativeSDK: Exception in com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer.create: java.lang.NullPointerException: null reference.

**Comment by hugohuang1111** [comment]
hm, google app id res is null? i'll try

**Comment by hugohuang1111** [comment]
i write a very sample code to test. and i can create room success.

1. tap Login
2. `login success` log show
3. tap create room
4. `room success` log show

i use cocos2d-x 3.17,  take a look at this:

https://github.com/sdkbox/sdkbox-sample-cpp317/tree/gpg

**Comment by yinjimmy** [comment]
no respond .
