### ISSUE TITLE
I cannot compile it on Android

### ISSUE THREAD

**Issue by kicpang** [sdkbox/sdkbox-sample-gpg#9]
I did searching for the solutions of these but did not help... Who can tell me how to fix it?

Android NDK: ERROR:/Users/kicpang/Downloads/sdkbox-cocos2d-x-binary/cocos/./prebuilt-mk/Android.mk:cocos2dx_internal_static: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/kicpang/Downloads/sdkbox-cocos2d-x-binary/cocos/./prebuilt-mk/../../prebuilt/android/x86_64/libcocos2dxinternal.a exists  or that its path is correct   
/Users/kicpang/Documents/android-ndk-r13b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
Error running command, return code: 2.

**Comment by yinjimmy** [comment]
`x86_64` ?

Just `armeabi` please.
